#!/bin/bash
set -eux
: "${AWS_PARALLELISM:=10}"
: "${XARGS_PARAMS:=-L 1 -P $AWS_PARALLELISM}"
MAX_AGE_TIMESTAMP="$(date --date "$MAX_AGE" +%s)"

aws sqs list-queues --queue-name-prefix "$QUEUE_NAME_PREFIX" \
| jq '.QueueUrls | .[]' \
| xargs ${XARGS_PARAMS[@]} aws sqs get-queue-attributes --attribute-names All --queue-url \
| jq ".Attributes | select(.ApproximateNumberOfMessages | tonumber >= ${MIN_PENDING_MESSAGES:-2000}) | select(.LastModifiedTimestamp | tonumber < $MAX_AGE_TIMESTAMP)" \
| jq '.QueueArn | split(":")[-1]' \
| xargs ${XARGS_PARAMS[@]} aws sqs get-queue-url --queue-name \
| jq '.QueueUrl' \
| tee /dev/tty \
| xargs ${XARGS_PARAMS[@]} aws sqs delete-queue --queue-url

